//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OpenQA.Selenium;
using System;


namespace Chomsky.PageObjects {
    
    
    public class SignIn : Page {
        
        public virtual By Email {
            get {
                return By.Id("#Email");
            }
        }
        
        public virtual By Password {
            get {
                return By.Id("#Password");
            }
        }
        
        public virtual By Login {
            get {
                return By.Id("#submit");
            }
        }
    }
}
