//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OpenQA.Selenium;
using System;


namespace Chomsky.PageObjects {
    
    
    public class google : Page {
        
        public virtual By SearchText {
            get {
                return By.Id("input[name=\'q\']");
            }
        }
        
        public virtual By SearchButton {
            get {
                return By.Id("input[type=\'submit\']");
            }
        }
    }
}
